/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface Episode {
  'title' : string,
  'duration' : bigint,
  'thumbnailUrl' : string,
  'description' : string,
  'tvShowId' : Principal,
  'seasonNumber' : bigint,
  'episodeNumber' : bigint,
  'videoUrl' : string,
}
export interface Movie {
  'title' : string,
  'duration' : bigint,
  'thumbnailUrl' : string,
  'description' : string,
  'genre' : string,
  'videoUrl' : string,
  'releaseYear' : bigint,
}
export interface TVShow {
  'title' : string,
  'thumbnailUrl' : string,
  'seasons' : bigint,
  'description' : string,
}
export interface _SERVICE {
  'addEpisode' : ActorMethod<[Episode], Principal>,
  'addMovie' : ActorMethod<[Movie], Principal>,
  'addTVShow' : ActorMethod<[TVShow], Principal>,
  'deleteEpisode' : ActorMethod<[], undefined>,
  'deleteMovie' : ActorMethod<[], undefined>,
  'deleteTVShow' : ActorMethod<[], undefined>,
  'getEpisode' : ActorMethod<[Principal], Episode>,
  'getEpisodesBySeason' : ActorMethod<[Principal, bigint], Array<Episode>>,
  'getEpisodesByTVShow' : ActorMethod<[Principal], Array<Episode>>,
  'getMovie' : ActorMethod<[Principal], Movie>,
  'getTVShow' : ActorMethod<[Principal], TVShow>,
  'updateEpisode' : ActorMethod<[Episode], undefined>,
  'updateMovie' : ActorMethod<[Movie], undefined>,
  'updateTVShow' : ActorMethod<[TVShow], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];