/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const Episode = IDL.Record({
  'title' : IDL.Text,
  'duration' : IDL.Nat,
  'thumbnailUrl' : IDL.Text,
  'description' : IDL.Text,
  'tvShowId' : IDL.Principal,
  'seasonNumber' : IDL.Nat,
  'episodeNumber' : IDL.Nat,
  'videoUrl' : IDL.Text,
});
export const Movie = IDL.Record({
  'title' : IDL.Text,
  'duration' : IDL.Nat,
  'thumbnailUrl' : IDL.Text,
  'description' : IDL.Text,
  'genre' : IDL.Text,
  'videoUrl' : IDL.Text,
  'releaseYear' : IDL.Nat,
});
export const TVShow = IDL.Record({
  'title' : IDL.Text,
  'thumbnailUrl' : IDL.Text,
  'seasons' : IDL.Nat,
  'description' : IDL.Text,
});

export const idlService = IDL.Service({
  'addEpisode' : IDL.Func([Episode], [IDL.Principal], []),
  'addMovie' : IDL.Func([Movie], [IDL.Principal], []),
  'addTVShow' : IDL.Func([TVShow], [IDL.Principal], []),
  'deleteEpisode' : IDL.Func([], [], []),
  'deleteMovie' : IDL.Func([], [], []),
  'deleteTVShow' : IDL.Func([], [], []),
  'getEpisode' : IDL.Func([IDL.Principal], [Episode], ['query']),
  'getEpisodesBySeason' : IDL.Func(
      [IDL.Principal, IDL.Nat],
      [IDL.Vec(Episode)],
      ['query'],
    ),
  'getEpisodesByTVShow' : IDL.Func(
      [IDL.Principal],
      [IDL.Vec(Episode)],
      ['query'],
    ),
  'getMovie' : IDL.Func([IDL.Principal], [Movie], ['query']),
  'getTVShow' : IDL.Func([IDL.Principal], [TVShow], ['query']),
  'updateEpisode' : IDL.Func([Episode], [], []),
  'updateMovie' : IDL.Func([Movie], [], []),
  'updateTVShow' : IDL.Func([TVShow], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const Episode = IDL.Record({
    'title' : IDL.Text,
    'duration' : IDL.Nat,
    'thumbnailUrl' : IDL.Text,
    'description' : IDL.Text,
    'tvShowId' : IDL.Principal,
    'seasonNumber' : IDL.Nat,
    'episodeNumber' : IDL.Nat,
    'videoUrl' : IDL.Text,
  });
  const Movie = IDL.Record({
    'title' : IDL.Text,
    'duration' : IDL.Nat,
    'thumbnailUrl' : IDL.Text,
    'description' : IDL.Text,
    'genre' : IDL.Text,
    'videoUrl' : IDL.Text,
    'releaseYear' : IDL.Nat,
  });
  const TVShow = IDL.Record({
    'title' : IDL.Text,
    'thumbnailUrl' : IDL.Text,
    'seasons' : IDL.Nat,
    'description' : IDL.Text,
  });
  
  return IDL.Service({
    'addEpisode' : IDL.Func([Episode], [IDL.Principal], []),
    'addMovie' : IDL.Func([Movie], [IDL.Principal], []),
    'addTVShow' : IDL.Func([TVShow], [IDL.Principal], []),
    'deleteEpisode' : IDL.Func([], [], []),
    'deleteMovie' : IDL.Func([], [], []),
    'deleteTVShow' : IDL.Func([], [], []),
    'getEpisode' : IDL.Func([IDL.Principal], [Episode], ['query']),
    'getEpisodesBySeason' : IDL.Func(
        [IDL.Principal, IDL.Nat],
        [IDL.Vec(Episode)],
        ['query'],
      ),
    'getEpisodesByTVShow' : IDL.Func(
        [IDL.Principal],
        [IDL.Vec(Episode)],
        ['query'],
      ),
    'getMovie' : IDL.Func([IDL.Principal], [Movie], ['query']),
    'getTVShow' : IDL.Func([IDL.Principal], [TVShow], ['query']),
    'updateEpisode' : IDL.Func([Episode], [], []),
    'updateMovie' : IDL.Func([Movie], [], []),
    'updateTVShow' : IDL.Func([TVShow], [], []),
  });
};

export const init = ({ IDL }) => { return []; };